Switch WebThings TDs from local to live instance, with instructions
w3c/wot-testing pull request #269
Opened 2022-03-17 18:27 UTC by benfrancis

2022-03-18 13:08 UTC, benfrancis commented
Don't know why the tab width got switched from two spaces to four which makes the diffs messy sorry, you can filter out whitespace changes on GitHub's diff viewer.

2022-03-20 23:14 UTC, egekorkan requested changes

2022-03-20 23:14 UTC, egekorkan commented on events/2022.03.Online/TD/WebThings/TDs/camera.td.jsonld
> +    "@context": "https://iot.mozilla.org/schemas",
this is actually causing the validation errors

2022-03-20 23:15 UTC, egekorkan commented
I have also fixed the actual validation in the meantime and I have committed the change to your branch so that the validation here also succeeds. This has led to me finding the actual error.

2022-03-21 13:26 UTC, egekorkan approved these changes

2022-03-21 13:26 UTC, merged