Implementation Description and Testimonials from Siemens and Bosch
w3c/wot-testing pull request #270
Opened 2022-03-17 20:08 UTC by egekorkan

- I have added testimonials from Siemens and Bosch
- I have added implementation descriptions of node-wot, sayWoT, ditto, editdor and playground

2022-03-17 20:10 UTC, egekorkan commented
Additionally, @sebastiankb, @thjaeckle and @fexpal can you have a look? I cannot add you as reviewers

2022-03-18 00:27 UTC, k-toumura approved these changes

2022-03-18 06:44 UTC, thjaeckle requested changes
I left some suggestions mostly regarding the Ditto implementation sections.

2022-03-18 06:44 UTC, thjaeckle commented on events/2022.03.Online/Architecture/Impls/ditto.html
> +  <p><b>Contributing Member Organizations:</b> Bosch.IO</p>
```suggestion
  <p>
    A service that provides APIs for managing digital twins and interacting with the 
    abstracted devices. Fetches linked Thing Models of digital twins and provides instance 
    specific Thing Descriptions for them.
  </p>
  <p><b>Usage:</b> Service</p>
  <p><b>Public Repository:</b> https://github.com/eclipse/ditto</p>
  <p><b>Website:</b> https://www.eclipse.org/ditto/basic-wot-integration.html</p>
  <p><b>Contributing Member Organizations:</b> Bosch.IO</p>
```

I would suggest the above instead - would that be ok?

2022-03-18 06:44 UTC, thjaeckle commented on events/2022.03.Online/Architecture/Impls/ditto.html
> +    environments with concepts native to Java.
```suggestion
    Eclipse Ditto offers a Java Module to use TDs and TMs inside Java
    environments with concepts native to Java, e.g. providing a builder API for creating 
    new TM/TD instances and rendering those to JSON strings and vice versa.
```

2022-03-18 08:22 UTC, felpal commented on events/2022.03.Online/Architecture/Testimonials/siemens.html
> +      Siemens also implements WoT in its sayWoT! offering that can be used IoT
```suggestion
      Siemens also implements WoT in its <a href="https://www.evosoft.com/digitalisierungsangebot/saywot/">sayWoT!</a> offering that can be used in IoT
```

Would it be possible to add this?

2022-03-18 10:12 UTC, egekorkan commented
@thjaeckle and @felpal I have incorporated your feedback

2022-03-18 10:37 UTC, thjaeckle approved these changes

2022-03-18 12:19 UTC, merged