Add ComboSecurityScheme with descriptions
w3c/wot-testing pull request #356
Opened 2022-06-22 13:01 UTC by FadySalama

This PR adds ComboSecurityScheme definitions for TUM Philips Hue devices with descriptions in both English and German

2022-06-24 11:09 UTC, egekorkan requested changes
My comments apply to all changed tds

2022-06-24 11:09 UTC, egekorkan commented on events/2022.06.Online/TD/philips-hue/TDs/tum-daylight.td.jsonld
> +    "security": "combo_sc",
Security is used twice

2022-06-24 11:09 UTC, egekorkan commented on events/2022.06.Online/TD/philips-hue/TDs/tum-daylight.td.jsonld
> +                    "href": "https://esiremotelab.esi.ei.tum.de:8081/LabLocal/api/17AvYQeLM2T8Z3r0e3BiEvb9Qdwt36yU2BudTxrn/sensors/1",
This should be updated to reflect apikey security scheme

2022-06-29 13:44 UTC, FadySalama commented
> Lookd good

@egekorkan I found the error that causes the test to fail. (See: [here](https://github.com/w3c/wot-thing-description/issues/1557))

2022-07-06 13:28 UTC, merged