TUM manual.csv
w3c/wot-testing pull request #374
Opened 2022-07-26 12:13 UTC by FadySalama

add manual.csv for TUM devices

2022-07-26 18:35 UTC, egekorkan commented
@FadySalama Not sure what the manual-tum means inside node-wot. did you mean the flask-tum implementation?

2022-07-29 14:56 UTC, egekorkan requested changes

2022-07-29 14:56 UTC, egekorkan commented on events/2022.07.Online/TD/flask-tum/manual.csv
> +"td-default-writeOnly","pass","The value associated with member writeOnly if not given MUST be assumed to have the default value false."
actually the default assertions make sense only for consumers since the Things here do not interpret this

2022-10-28 15:57 UTC, mmccool commented
I see there are changes requested still.  I will watch for updates, but would like to update the IRs soon.  I'll deal with the other PRs in the meantime (and leave this PR open) but please complete this PR as soon as possible and when it is ready I will merge and incorporate in the IRs.

2022-10-28 16:01 UTC, mmccool commented
Also, might want to rebase first as there were some overlapping changes to manual-tms etc.

2022-10-30 12:00 UTC, egekorkan commented
I think that main thing to change is adding the manual.csv here

2022-11-02 21:35 UTC, FadySalama commented
Sorry but the review is outdated, please recheck and tell me what needs to change so we can close this PR

2022-11-03 10:01 UTC, egekorkan commented
@FadySalama simply move the manual csv for the manual tms to https://github.com/w3c/wot-testing/tree/main/data/input_2022/TD/fischertechnik-factory-simulator since I have renamed the directory there. You will need to adjust the bash script accordingly. 

Flask is fine :)

2022-11-24 21:20 UTC, egekorkan commented
There are too many merge conflicts and similar issues for a simple PR, please see #484

2022-11-28 08:20 UTC, FadySalama commented
Should I close this? @egekorkan

2022-11-28 12:26 UTC, egekorkan commented
Yes this can be closed

2022-11-28 12:26 UTC, closed without merging