Updating all manual csvs
w3c/wot-testing pull request #395
Opened 2022-07-29 15:49 UTC by egekorkan

I am updating the main and moving the changes to all implementations. Not sure if I will manage to finish today, thus draft for now

2022-07-31 11:53 UTC, egekorkan commented
To have it as a list. 

To remove from each manual.csv:
- td-context-default-language-direction-heuristic
- td-context-default-language-direction-inference
- td-context-ns-multilanguage-text-direction-infer
- td-default-format-pop
- tm-placeholder-retyping
- tm-tmRef-overwrite
- well-known-operation-types-only

To add:
- privacy-auth-users-only
- privacy-centralized-ids
- privacy-essential-metadata-only
- privacy-immutable-id-as-property
- privacy-mutable-id-ownership
- privacy-mutable-identifiers
- privacy-td-pii
- privacy-temp-id-metadata
- sec-body-name-json-pointer-type
- sec-inj-no-intl-markup
- sec-inj-sanitize
- security-context-secure-fetch
- security-jsonld-expansion
- security-mutual-auth-td
- security-no-execution
- security-oauth-limits
- security-remote-context
- security-server-auth-td
- security-static-context
- security-update-contexts
- td-context-ns-td10-namespacev10
- td-security-extension
- td-text-direction-first-strong
- td-text-direction-language-tag
- thing-model-td-generation-processor-extends
- thing-model-td-generation-processor-forms
- thing-model-td-generation-processor-imports
- thing-model-td-generation-processor-placeholder
- thing-model-td-generation-processor-required
- thing-model-td-generation-processor-type
- tm-placeholder-replacement
- tm-ref-recursive-extensions
- tm-tmRef-overwrite-possibility
- tm-tmRef-overwrite-process
- tm-tmRequired-resolver

To possibly change order:
- td-default-AdditionalResponseContentType
- td-default-observable

To rename:
- tm-tmRef-2 -> tm-tmRef2

2022-07-31 13:36 UTC, egekorkan commented
Removal and renaming was easy but adding new assertions is not. Each implementor needs to check if all the assertions above are in their manual.csv . Some of the assertions in the list have 16 hits in a search and some have 18. This means, not all manual.csvs are in sync

2022-08-01 13:51 UTC, mmccool commented
Looks ok, but it looks like some of the new files have blank lines where an old assertion got deleted.  I don't *think* this will cause a problem with tooling, but it might (worst case, a tool might silently ignore things below the blank line) so it would probably be better if the blank lines were removed.  When I get a chance I will edit the PR to do that, then merge it, then update the TD testing results and implementation report.

2022-08-01 13:57 UTC, mmccool requested changes

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Older/TUM/tum-PhilipsHUE.csv
> +
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Older/TUM/tum-microPythonBare.csv
> +
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Older/TUM/tum-mqttTest-retain.csv
> +
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Older/TUM/tum-mqttTest.csv
> +
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Older/TUM/tum-pythonFlask.csv
> +
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Older/panasonic-client-browser/TDs/panasonic-client-browser.csv
> +"","not-impl","not supported"
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Older/panasonic-client-nodered/TDs/panasonic-client-nodered.csv
> +
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Older/panasonic-server-simulator/TDs/panasonic-server-simulator.csv
> +
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Results/huawei-cf-secure-psk.csv
> +,
```suggestion
```

2022-08-01 13:57 UTC, mmccool commented on data/input_2022/TD/Results/panasonic-server-simulator.csv
> +,
```suggestion
```

2022-08-01 13:58 UTC, mmccool commented
Made some suggested edits to get rid of "junk" lines.  @egekorkan can you review and if they look good, update the PR?

2022-08-01 16:00 UTC, mmccool approved these changes

2022-08-01 16:03 UTC, mmccool commented
junk lines fixed, merging, will do any cleanup after attempting to re-run tooling.

2022-08-01 16:03 UTC, merged